services:
  wireguard:
    container_name: wireguard
    build: .
    image: wg:latest
    depends_on:
      - pihole
    networks:
      - private
    ports:
      - "${WG_PORT:-51820}:${WG_SERVER_PORT:-51820}/udp"
    environment:
      - WG_KEYS_BASE64=${WG_KEYS_BASE64}
      - WG_SERVER_PRIVATE_KEY=${WG_SERVER_PRIVATE_KEY}
      - WG_SERVER_IP=${WG_SERVER_IP:-10.6.0.1/24}
      - WG_SERVER_PORT=${WG_SERVER_PORT:-51820}
      - WG_CLIENT_PUBLIC_KEY=${WG_CLIENT_PUBLIC_KEY}
      - WG_CLIENT_IP=${WG_CLIENT_IP:-10.6.0.2/32}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped

  nginx:
    container_name: nginx
    depends_on:
      - pihole 
    build:
      context: proxy
    image: nginx:latest
    networks:
      private:
        ipv4_address: ${NGINX_IP:-10.7.107.10}
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    depends_on:
      - cloudflared
    networks:
      private:
        ipv4_address: ${PIHOLE_IP:-10.7.107.101}
    ports:
      - "${PIHOLE_DNS_PORT:-53}:53/tcp"
      - "${PIHOLE_DNS_PORT:-53}:53/udp"
      - "${PIHOLE_WEB_PORT:-8080}:80/tcp"
    environment:
      - TZ=${TZ:-America/New_York}
      - WEBPASSWORD=${PIHOLE_WEBPASSWORD}
      - PIHOLE_DNS_=${PIHOLE_DNS_IP:-1.1.1.1}
    volumes:
      - './docker-vol/etc-pihole/:/etc/pihole/'
      - './docker-vol/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: proxy-dns --address 0.0.0.0 --port ${CLOUDFLARED_DNS_PORT} --upstream https://1.1.1.1/dns-query --upstream https://1.0.0.1/dns-query --metrics 0.0.0.0:${CLOUDFLARED_METRIC_PORT}
    networks:
      private:
        ipv4_address: ${CLOUDFLARED_IP:-10.7.107.111}
    ports:
      - "${CLOUDFLARED_DNS_PORT:-5053}:5053"
      - "${CLOUDFLARED_METRIC_PORT:-8053}:8053"
    restart: unless-stopped
    healthcheck:
      test: ["dig", "@${CLOUDFLARED_IP}", "-p", "5053", "google.com"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
      start_interval: 5s

networks:
  private:
    ipam:
      driver: default
      config:
        - subnet: "${DOCKER_COMPOSE_NETWORK_RANGE:-172.23.0.0/24}"
